//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DR.NummerStripper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MA;http://ma:7000/#!/search/item?q={prdNbr}</string>
  <string>OD PubPlan;https://odpubplan/Publication/Search?query={prdNbr}</string>
  <string>PSDB Admin;http://mu.net.dr.dk/admin/#searchString={prdNbr}&amp;searchCategories=10%2C20%2C30%2C90&amp;limit=20&amp;channelType=TV%2CRADIO</string>
  <string>UQC;http://mccpweb/qclogapi/overview?pro_number={prdNbr}</string>
  <string>Manis;http://manis-od.net.dr.dk/api/mediaassets?productionNumber={prdNbr}</string>
  <string>Marvin;http://marvin/?environment=Production#!filter={prdNbr}</string>
  <string>WOCache od pubs;http://wocache/api/od-publications/search/findByProductionNumber?productionNumber={prdNbr}</string>
  <string>WOCache flow;http://wocache/api/flow-publications/search/findByProductionNumber?productionNumber={prdNbr}</string>
  <string>OD3 LogViewer;http://odps/od-dashboard/LogViewer?correlationId={prdNbr}</string>
  <string>OD3 Pub Viewer;http://odps/od-dashboard/PublicationViewer?productionId={prdNbr}</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ProductionNumberLinks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProductionNumberLinks"]));
            }
        }
    }
}
